FROM mcr.microsoft.com/devcontainers/java:17-bullseye

# Instalar Node.js para desarrollo frontend si es necesario
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs
